### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by progsmile** [alex-ander-is/revenger#1]
How many instances are created? I see 2 from `startTemplate.sh`?

**Comment by alex-ander-is** [comment]
Until the step 14 everything belongs to the template image preparation. The image includes pre-installed packages and docker image. One per region.
Once the image from template is ready, we can utilize already existed instances. `startTemplate.sh` brings back online them. From now you can create as many instances as you want from the image on top of these two instances.

**Comment by progsmile** [comment]
Great!
