### ISSUE TITLE
wipe.sh fails to remove security groups

### ISSUE THREAD

**Issue by elvisfox** [alex-ander-is/revenger#7]
Tested on version 2dda017fa689ec3d3684f5032ae1cd4420ab5943

> The removing of SSH Security Groups was not succesfull.

I have removed security groups manually and tried several times install.sh->wipe.sh without success.
The rest of items were cleaned up correctly.

**Comment by JekaNS** [comment]
There is no determinate exception. In my case I've got problem "The removing of AMI images was not succesfull"
I think it's be cause in wipe.sh, instance termination is asynchronous. We need to wait while instances will gracefully terminating

**Comment by elvisfox** [comment]
Works for me in 7ff6717fa9765fec56a2949db910b640ca4c8aae

**Comment by alex-ander-is** [comment]
Fixed
